- Cargo.lock
- Cargo.toml
- src/svm/main.rs
structopt uses an old version of clap and it causes some trouble with downstream dependencies (e.g. foundry)
> replace structopt with clap3

- src/platform.rs
If you use `svm-rs` as a library then some platforms might still show up as supported even though they are not x86_64 (e.g. Linux aarch64, see https://github.com/gakonst/foundry/issues/597)
> Check target architecture as well

- list/linux-aarch64.json
- list/linux-arm64-old.json
- src/lib.rs
- src/platform.rs
- src/releases.rs
Adding support for linux aarch64 architecture.
`solc` binaries fetched from https://github.com/nikitastupin/solc/tree/main/linux/aarch64
> feat: add support for linux aarch64 binaries

- src/lib.rs
- src/releases.rs
this avoids potential issues in the future where the solc binaries in the repo
get updated to a malicious binary
pin is https://github.com/nikitastupin/solc/tree/3890b86a62fe6b8efd2f643f4adcd854f478b623
> fix: pin arm64 solc commit

- src/releases.rs
Returns the macOS AArch64 releases in `blocking_all_releases` as we do in `all_releases`.
> fix: macos M1 releases in `blocking_all_releases`

- list/macosx-aarch64.json
- src/releases.rs
this was done [here](https://github.com/roynalnaruto/solc-builds/commit/d1388e554684c5a10954d0c80182e671c4fc2ade) but the change was not ported over. this must be merged ASAP as otherwise all checksums checks will fail
this is not an ideal solution as we need to keep the 2 repos in sync, ideally only 1 checksum file should be used
> [p0] fix: update solc checksums for prod builds

- src/releases.rs
Related to issue: https://github.com/ethereum/solidity/issues/12784
This is a temporary fix to allow support for all `solc` versions for MacOS users. If the `solc` version in question is `>= 0.8.5` (which have been natively compiled and hosted in [`solc-builds`](https://github.com/roynalnaruto/solc-builds)) then we use those. For all other versions under `0.8.5` we fallback to `macos-amd64` builds that require Rosetta support.
We expect to eventually fix the compilation issues in the above mentioned GH issue, but for now this is the most reasonable solution to support as many versions as possible via [`Foundry`](https://github.com/gakonst/foundry)
> fix: fallback to rosetta for versions under natively compilable v0.8.5

- src/lib.rs
returning the path prevents an additional `version_path` lookup
> feat: return solc file path after install

- Cargo.lock
- Cargo.toml
- src/platform.rs
- src/releases.rs
- svm-builds/Cargo.toml
- svm-builds/build.rs
- svm-builds/src/lib.rs
Embed Release information in a crate so we don't need to query `svm::releases` all the time
Add a new crate (svm-builds) that fetches all available releases during build and generates constants
expanded output:
```rust
pub const SOLC_VERSION_0_3_6: semver::Version = semver::Version::new(0, 3, 6);
pub const SOLC_VERSION_0_3_6_CHECKSUM: &str =
"02d581b5b373d8160b9e75d690dd2ee898c3e0f6a39bbda54cd0698224c09df4";
pub const SOLC_VERSION_0_4_0: semver::Version = semver::Version::new(0, 4, 0);
pub const SOLC_VERSION_0_4_0_CHECKSUM: &str =
"bba6e2c33935259c478060501a7fb0ee1db4b0c56567356c9d01b6ec0491a558";
pub const SOLC_VERSION_0_4_1: semver::Version = semver::Version::new(0, 4, 1);
pub const SOLC_VERSION_0_4_1_CHECKSUM: &str =
"2de730163c80670b2f4c1ef78dc77ab13f757aad1ead044761821293275c382b"; …
```
> feat(builds): add svm-builds crate

- Cargo.lock
- Cargo.toml
- src/lib.rs
* this replaces the old locking code with [`fs2::FileExt`](https://docs.rs/fs2/latest/fs2/trait.FileExt.html)
* also bumps timeout to 60 secs, default is 30 and can be exceeded easily on slow networks
> feat: use fs2 for locking and increase request timeout to 60 secs

- .github/workflows/ci.yml
- src/lib.rs
Bumps up the `REQUEST_TIMEOUT` for fetching `solc` binary. Requested in https://github.com/gakonst/foundry/issues/1223
> chore: bump up request timeout for fetching solc binary

- src/error.rs
- src/lib.rs
checks that downloading was successful this prevents that we end up downloading a wrong github URL and fail with a checksums don't match error
> feat: add response status check

- src/releases.rs
also retains `releases` object so that we don't end up with invalid entries if there's no matching native release yet
> fix: retain old releases as well

- src/error.rs
- src/lib.rs
- src/platform.rs
Implements https://github.com/roynalnaruto/svm-rs/issues/36.
This works by using `patchelf` to modify the dynamic linker in the installed solc binaries to use the nixos provided one (instead of the standard `/lib64/ld-linux-x86-64.so.2` which is not present on nixos).
Currently I've only tested locally with a few versions, and afaict it's working OK. I'm not sure what the automated testing strategy here is, but I would be more than happy to add some nixos specific tests / CI steps if you want.
Some more work will be needed to point the binaries to a nix provided version of z3/cvc (needed for the SMTChecker to work), but I'm going to leave that for another PR.
> automatically patch binaries for nixos

- svm-builds/Cargo.toml
- svm-builds/build.rs
network access is blocked during docrs builds: https://docs.rs/about/builds
* add offline feature that generates empty constants
> feat: add offline feature

- Cargo.lock
- svm-builds/Cargo.toml
- svm-builds/build.rs
`[package.metadata.docs.rs]` settings are only respected for the crate that's being published so current behaviour will cause docs rs build failures in downstream deps
it's recommended to check for DOCS_RS env var: https://docs.rs/about/builds#detecting-docsrs
so if not offline mode also check for DOCS_RS env var
> chore: check for DOCS_RS flag

- svm-builds/build.rs
Noticed this issue while publishing `svm-builds`: https://github.com/roynalnaruto/svm-rs/blob/master/svm-builds/build.rs#L151-L154
`generate_offline` is not compiled when `_offline` feature is not enabled. But the above snippet tries to use it.
I'm simply removing the `#[cfg(feature = "_offline")]` feature gate, so that `generate_offline` can be used in all cases where it's required.
@mattsse please have a look :)
> fix: remove cfg for defining function

- src/releases.rs
Only `0.8.15` could be compiled without build errors.
> solc-builds with z3 smt solver support

- Cargo.lock
- Cargo.toml
The previous version of the zip package has an outdated transitive Rust Crypto dependency that conflicts with newer Rust Crytpo crates, so it's important to update.
The master branch of the `zip` package already contains the new Rust Crytpo dependencies, but it's been waiting for a release for three months now so this commit switches to the updated `binstall-zip` fork by the `cargo-bins` team.
Fore more context, please see: https://github.com/roynalnaruto/svm-rs/pull/62
> chore: switch `zip` to `binstall-zip`

- Cargo.lock
- Cargo.toml
- src/lib.rs
Follow up from #65 :
The original `zip` crate cut a new release and the `binstall-zip` fork is now deprecated.
> chore: switch `binstall-zip` to `zip`

- src/lib.rs
From https://github.com/roynalnaruto/svm-rs/pull/48#discussion_r1109165184
solc 0.7.6 was the first version to be dynamically-linked against ld loader, and therefore doesn't work on NixOS.
> nixos: patch solc 0.7.6, first dynamically-linked version

- Cargo.lock
- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/bin/svm-bin/main.rs
- crates/svm-rs/src/lib.rs
Adding support to a [widely adopted standard](https://wiki.archlinux.org/title/XDG_Base_Directory) for user-specific application configuration/data files and directories, aimed at uncluttering the user's home directory.
~/.skm still works if that directory already exists, for backwards compatibility. If it does not exist, then the updated code will follow specification values.
> Support XDG directory specification

- Cargo.lock
- crates/svm-builds/build.rs
Check the `SVM_RELEASES_LIST_JSON` env variable first, and if it's defined then try loading the releases list from a local file.
Fixes #79
> Allow to override the releases list manually

- Cargo.lock
- crates/svm-builds/Cargo.toml
- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/lib.rs
- crates/svm-rs/src/releases.rs
> feat: `0.8.22` support

- crates/svm-rs/src/lib.rs
When running Foundry in CI, I encountered an issue where if multiple instances of Foundry were launched at the same time, compiling Solidity source in different directories, one would sometimes fail with an `AlreadyExists` error.
Upon investigating, I noticed that there is indeed a file lock to prevent multiple solc versions from being installed at the same time, but that this file lock does not apply to creating the SVM directory.
This PR adds error hanlding to the `setup_data_dir` function to handle a race condition to create the SVM directory.
> Fix race condition between instances of svm in setting up the SVM directory

- Cargo.lock
- crates/svm-rs/src/bin/svm-bin/install.rs
- crates/svm-rs/src/bin/svm-bin/list.rs
- crates/svm-rs/src/bin/svm-bin/main.rs
- crates/svm-rs/src/bin/svm-bin/remove.rs
- crates/svm-rs/src/bin/svm-bin/usev.rs
- crates/svm-rs/src/bin/svm-bin/utils.rs
- crates/svm-rs/src/releases.rs
Refactors the CLI code to using the `cmd.run(args)` pattern we use in foundry. Functionality is preserved.
> feat(`cli`): CLI refactor

- README.md
closes #106
update git url for cargo install --git
> chore: update readme install instructions

- Cargo.lock
- README.md
- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/install.rs
- crates/svm-rs/src/releases.rs
solc now ships universal macos binaries, so we no longer have to build them for https://github.com/alloy-rs/solc-builds
> feat: add support for 0.8.25

- Cargo.lock
- Cargo.toml
breaking changes on last release
> chore: release 0.4.0

- crates/svm-rs/src/install.rs
- crates/svm-rs/src/releases.rs
add missing checks for macos aarch64
> fix: filter for universal macos

- Cargo.lock
- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/error.rs
- crates/svm-rs/src/install.rs
The `zip` crate hasn't been updated in almost a year, and has a number of bugs that can cause panics when trying to process an invalid zip file. This PR replaces it with `zip_next`, a fork I actively maintain.
> Replace `zip` with `zip_next`

- crates/svm-rs/src/releases.rs
Small performance optimization to avoid `302` redirect, requested in https://github.com/foundry-rs/foundry/issues/7440
> perf: use `raw.githubusercontent.com` direct link to avoid 302 redirects

- crates/svm-rs/src/install.rs
From https://github.com/foundry-rs/foundry/issues/8507:
Downloading the solc compiler is timing out too quickly. This makes it impossible to use forge with slow internet speeds.
```
$ forge build -- --vvvv
Error: 
error decoding response body
Context:
- Error #0: request or response body error
- Error #1: operation timed out
```
- The solc binary size for mac has increased from 37MB to 79MB since v0.8.23.
- The timeout for forge to download the binary is less than 3 minutes.
- On a slow internet connection, there is not enough time for the download to complete before timing out.
- Increase the timeout limit for downloads to 10 minutes
Closes: https://github.com/foundry-rs/foundry/issues/8507
> feat: increase `solc` download timeout window to 10 minutes from 2 minutes

- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/error.rs
- crates/svm-rs/src/install.rs
While running some tests involving Foundry, I have encountered "text file busy" errors, like described in #16.
This PR is currently organized as two commits:
- Add `can_install_while_solc_is_running` test - intentionally fails with "text file busy"
- Eliminate "test file busy" errors - installs solc to a temporary file and then renames it, so that the previous test passes
Nits are welcome.
EDIT: ~I'll be happy to fix the typo in the commit message, once you've had a chance to review.~ Fixed.
> Eliminate "text file busy" errors

- Cargo.lock
- Cargo.toml
- crates/svm-builds/Cargo.toml
- crates/svm-builds/build.rs
- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/bin/solc/main.rs
- crates/svm-rs/src/lib.rs
- crates/svm-rs/src/platform.rs
- crates/svm-rs/src/releases.rs
> feat: improve release profile

- Cargo.lock
- crates/svm-rs/Cargo.toml
fs4 version 0.10 was yanked from crates.io thus `cargo install` is broken now.
This PR bumps fs4 version to the latest one fixing the installation issue
> Bump fs4 version to 0.12

- .config/nextest.toml
- .github/workflows/ci.yml
- crates/svm-rs/src/install.rs
- crates/svm-rs/src/paths.rs
- crates/svm-rs/src/platform.rs
Fixes https://github.com/alloy-rs/svm-rs/issues/149.
> fix: more robust nixos check

- crates/svm-rs/src/releases.rs
The updated commit adds solc versions 0.8.25-0.8.28.
Context: https://github.com/alloy-rs/solc-builds/pull/14.
> feat: update android-aarch64 repo link

- crates/svm-rs/src/install.rs
Since 0.8.29, the builds are fully static again. The patching for nixos is not only unnecessary, but triggers errors.
This fixes it.
See https://github.com/ethereum/solidity/releases/tag/v0.8.29
> Linux release builds are fully static again and no longer depend on `glibc`.
> svm: Disable NixOS patching after 0.8.28

- Cargo.lock
- crates/svm-rs/Cargo.toml
- crates/svm-rs/src/install.rs
```
Updating crates.io index
Locking 95 packages to latest compatible versions
Updating anyhow v1.0.95 -> v1.0.97
Updating bitflags v2.8.0 -> v2.9.0
Updating bumpalo v3.16.0 -> v3.17.0
Removing byteorder v1.5.0
Updating bytes v1.9.0 -> v1.10.1
Updating cc v1.2.10 -> v1.2.18
Updating clap v4.5.27 -> v4.5.35
Updating clap_builder v4.5.27 -> v4.5.35
Updating clap_derive v4.5.24 -> v4.5.32
Updating console v0.15.10 -> v0.15.11
Updating deranged v0.3.11 -> v0.4.0
Updating either v1.13.0 -> v1.15.0
Updating equivalent v1.0.1 -> v1.0.2
Updating errno v0.3.10 -> v0.3.11
Updating flate2 v1.0.35 -> v1.1.1
Adding getrandom v0.3.2
Updating http v1.2.0 -> v1.3.1
Updating http-body-util v0.1.2 -> v0.1.3
Updating httparse v1.10.0 -> v1.10.1
Updating hyper-util v0.1.10 -> v0.1.11
Updating …
```
> chore(deps): cargo update

- README.md
- crates/svm-rs/src/bin/svm-bin/main.rs
This PR adds the following subcommand aliases:
- `ls` for `list`
- `i` for `install`
- `rm` for `remove`
It's a small change, but I think it will improve usability (especially `ls`, which is very common).
Here is a comparison with other version managers, for reference:
`svm-rs` | [`solc-select`](https://github.com/crytic/solc-select) | [`fnm`](https://github.com/Schniz/fnm) | [`nvm`](https://github.com/nvm-sh/nvm/) | [`uv`](https://github.com/astral-sh/uv) (using `uv python`)
--- | --- | --- | --- | ---
`list` | N/A (uses `install` without an argument to list all versions) | `list`, `ls` | `list`, `ls` | `list`, `ls`
`install` | `install` | `install`, `i` | `install`, `i` | `install`
`remove` | N/A | `uninstall`, `uni` | `uninstall` | `uninstall`
While updating the `README` to add the …
> feat: add aliases `ls`, `i`, and `rm`
